### ISSUE TITLE
není redirect z http na https

### ISSUE THREAD

**Issue by benabraham** [petrapavlis/projekt-narkolepsie#4]
Je dobré, protože web by měl mít jednu verzi a to na https.

https://docs.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

**Comment by petrapavlis** [comment]
snad hotovo? jestli jsem to pochopila a udělala správně🤣 děkuji za rady - jsem začátečník a trochu se v tom plácám místy...😁

**Comment by benabraham** [comment]
Jasně, stačí si zkusit otevřít http://narkolepsie.usinam.cz/ a pokud je výsledná adresa https://… je tam přesměrování (redirect) a to je přesně to, co je třeba.
