### ISSUE TITLE
Obrázky (hlavně pozadí hlavičky a patičky) jsou příliš velké.

### ISSUE THREAD

**Issue by benabraham** [petrapavlis/projekt-narkolepsie#5]
2 MB je opravdu hodně a lze to stáhnout, aniž by byla viditelná změna na zlomek datkové velikosti i ve formátu PNG.

například takto:
![dark-blue-watercolor-header](https://user-images.githubusercontent.com/334494/86488003-fa790780-bd5f-11ea-8af2-1a6a7a4fab9f.png)

**Comment by benabraham** [comment]
Mrkněte na https://squoosh.app/ https://pngquant.org/, případně služby typu https://tinypng.com/

Taky by pomohlo zbavit obrázek zbytečného šumu v té průhlednosti a asi obecně ta průhlednost není třeba.
![image](https://user-images.githubusercontent.com/334494/86488274-c5b98000-bd60-11ea-840a-f5e8c9bc3fb8.png)

**Comment by petrapavlis** [comment]
Všechny obrázky jsem prohnala přes tinypng před zveřejněním projektu, ale asi jsem někde udělala chybu. Projela jsem to znovu a stáhlo to o nějakých dalších 40%. Mělo by to teď být lepší a stránka se načítá podstatně rychleji.

**Comment by petrapavlis** [comment]
a děkuju za tipy na ty další dva nástroje
