### ISSUE TITLE
než se načte pozadí hlavičky, je skoro nečitelná

### ISSUE THREAD

**Issue by benabraham** [petrapavlis/projekt-narkolepsie#6]
![image](https://user-images.githubusercontent.com/334494/86488476-614af080-bd61-11ea-8e4f-b8a5d15e983d.png)

Řešením je nastavit stejnému elementu i `background-color` na nějakou podobnou z toho obrázku, něco jako `#2e569e`, takže než se načte obrázek, je tam ta plná barva. A taky to líp vypadá při načítání.

**Comment by petrapavlis** [comment]
Zdravím a díky za upozornění. Tak nějak jsem o tom věděla, ale zatím jsem si nenašla čas to doladit. Background-color jsem dodala. Ono to tam původně bylo, ale pracovaly jsme na projektu ve dvojici a z počátku jsme zápasily s gitem, mergem a mnoha změnami, takže to z toho asi někde vypadlo v procesu.
